-- Migration: Add Processing Unit partners master data

ALTER TABLE public.master_partners ADD COLUMN IF NOT EXISTS district TEXT;

-- Ensure unique constraint on (partner_name, partner_type) exists for ON CONFLICT clause
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'master_partners_partner_name_partner_type_key'
    ) THEN
        ALTER TABLE public.master_partners ADD CONSTRAINT master_partners_partner_name_partner_type_key UNIQUE (partner_name, partner_type);
    END IF;
EXCEPTION
    WHEN duplicate_table THEN NULL;
    WHEN others THEN NULL;
END $$;

INSERT INTO public.master_partners (partner_name, partner_type, address, district, state, state_code, pincode, gstin)
VALUES
('ASHOK PROCESS', 'Processing Unit', 'M/S. ASHOK PROCESSING MILLS, GROUND FLOOR 130/1 ARUMUGA PILLAI THOTTAM ROAD, ANNADHANAPATTI, SALEM - 636006', 'SALEM', 'TAMIL NADU', '33', '636006', '33EEPPA7279V1ZY'),
('JAI SAKTHI', 'Processing Unit', 'M/S. SRI JAYASAKTHI PROCESSING, 2/612A KALARAMPATTI MAIN ROAD, ERUMAPALAYAM, SALEM - 636015', 'SALEM', 'TAMIL NADU', '33', '636015', '33ACWPV6237D1ZF'),
('VAIBHAV PROCESSING MILLS PVT LTD', 'Processing Unit', 'M/S VAIBHAV PROCESSING MILLS PVT LTD, NO. 194/2F, MLR THOTTAM, BHAVANI MAIN ROAD, MAYAPURAM, R.N.PUDUR (PO), ERODE - 638005', 'ERODE', 'TAMIL NADU', '33', '638005', '33AARFV4074A1Z7'),
('V.K.S.TEXTILES', 'Processing Unit', 'M/S.V.K.S.TEXTILES, SF NO-18-1C, D.NO.2/183, YKS KATHIRVEL MAHAL OPPOSITE, SALEM BYE-PASS ROAD, KOMARAPALAYAM, NAMAKKAL-638183', 'NAMAKKAL', 'TAMIL NADU', '33', '638183', '33AEUPD9055J1ZF'),
('ROYAL RAINBOW PROCESS,', 'Processing Unit', 'M/S. ROYAL RAINBOW PROCESS, 239/5-B, 273/5, KONGAMPALAYAM ROAD, GANGAPURAM, ERODE-638102', 'ERODE', 'TAMIL NADU', '33', '638102', '33ABEFR8259H1Z3'),
('OM SAKTHI WASHING CENTRE,', 'Processing Unit', 'M/S. OM SAKTHI WASHING CENTRE, 5/37, DR.NAVALAR NAGAR,(NEAR A.L.C.) ERUMAPALAYAM P.O, SALEM-636015', 'SALEM', 'TAMIL NADU', '33', '636015', '33ASHPR4486F1ZI'),
('KAMATCHI EXPORT WASHING,', 'Processing Unit', 'M/S. KAMATCHI EXPORT WASHING, 55/A-4 PUTHUR ITTERI ROAD, NETHIMEDU, SALEM - 636002.', 'SALEM', 'TAMIL NADU', '33', '636002', '33ALMPV3431E1ZE'),
('M/S. N.R.P. TEX', 'Processing Unit', 'M/S. N.R.P. TEX, 140-7, BHARATHIYAR STREET, NEAR CAMEL MARK MITTAI COMPANY, OPP. VINAYAGA NURSERY SCHOOL, KALARAMPATTY, SALEM-636006', 'SALEM', 'TAMIL NADU', '33', '636006', '33ALBPR2700F1Z7'),
('M/S. MRC MILLS PRIVATE LIMITED.', 'Processing Unit', 'UNIT-2, PLOT NO. A-5/1, SIPCOT INDUSTRIAL ESTATE, CUDDALORE - 607 005.', 'CUDDALORE', 'TAMIL NADU', '33', '607005', '33AAGCM5692R1ZO'),
('M/S.SHREE SHANGARA SAKTHI MILLS,', 'Processing Unit', 'M/S.SHREE SHANGARA SAKTHI MILLS, B.P.AGRAHARAM , PADHAVEE THOTTAM, BHAVANI MAIN ROAD, ERODE-638005', 'ERODE', 'TAMIL NADU', '33', '638005', '33AATFS384731ZT'),
('M/S. SSM PROCESSING MILLS.', 'Processing Unit', 'M/S. SSM PROCESSING MILLS, KOMARAPALAYAM, NAMAKKAL', 'SALEM', 'TAMIL NADU', '33', '638183', '33AACCS9415J1Z9')
ON CONFLICT (partner_name, partner_type) 
DO UPDATE SET 
    address = EXCLUDED.address,
    district = EXCLUDED.district,
    state = EXCLUDED.state,
    state_code = EXCLUDED.state_code,
    pincode = EXCLUDED.pincode,
    gstin = EXCLUDED.gstin;
